name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'  # Specific compatible version
        cache: 'npm'
        cache-dependency-path: my-react-portfolio/package-lock.json
    
    - name: Install dependencies
      run: |
        cd my-react-portfolio
        npm install
    
    - name: Build React App
      run: |
        cd my-react-portfolio
        npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: my-react-portfolio/build
